version: "3"

services:
  mysql:
    image: percona:5.7.30
    container_name: mysql
    hostname: mysql

    ports:
      - "3306:3306"

    environment:
      - MYSQL_ROOT_PASSWORD="root"

    user: root

#  docker run -it --name mysql -h mysql -p 3306:3306 \
#  -e MYSQL_ROOT_PASSWORD="root" \
#  -d percona:5.7.30

